# Generated by Django 3.1.5 on 2021-01-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab1',
            options={'managed': False},
        ),
    ]
