# Generated by Django 3.1.5 on 2021-01-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210114_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab1',
            options={},
        ),
    ]
