# Generated by Django 3.1.5 on 2021-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210114_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
