# Generated by Django 3.1.5 on 2021-01-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210114_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab1',
            options={'managed': False},
        ),
    ]
