# Generated by Django 3.1.5 on 2021-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210114_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab2',
            name='bill_payeraccountid',
            field=models.TextField(blank=True, db_column='PayerAccountId', null=True),
        ),
    ]
