# Generated by Django 3.1.5 on 2021-01-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210114_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tab2',
            new_name='Tab3',
        ),
        migrations.AlterModelTable(
            name='tab3',
            table='tab3',
        ),
    ]
