# Generated by Django 3.1.5 on 2021-01-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210114_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab2',
        ),
    ]
