# Generated by Django 3.1.5 on 2021-01-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_tab2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab2',
        ),
    ]
