# Generated by Django 3.1.5 on 2021-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_delete_tab2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('field1', models.AutoField(primary_key=True, serialize=False)),
                ('bill_payeraccountid', models.TextField(blank=True, db_column='bill/PayerAccountId', null=True)),
                ('lineitem_usageaccountid', models.TextField(blank=True, db_column='lineItem/UsageAccountId', null=True)),
                ('lineitem_usagestartdate', models.TextField(blank=True, db_column='lineItem/UsageStartDate', null=True)),
                ('lineitem_usageenddate', models.TextField(blank=True, db_column='lineItem/UsageEndDate', null=True)),
                ('lineitem_usageamount', models.FloatField(blank=True, db_column='lineItem/UsageAmount', null=True)),
                ('lineitem_unblendedrate', models.FloatField(blank=True, db_column='lineItem/UnblendedRate', null=True)),
                ('lineitem_unblendedcost', models.FloatField(blank=True, db_column='lineItem/UnblendedCost', null=True)),
                ('product_productname', models.TextField(blank=True, db_column='product/ProductName', null=True)),
            ],
            options={
                'db_table': 'tab',
                'managed': False,
            },
        ),
    ]
