# Generated by Django 3.1.5 on 2021-01-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_tab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab1',
        ),
    ]
